version: "3"
services:
    flaskapp:
        image: markgowans/flaskapp
        networks:
            - app
        command: python myproject.py
        deploy:
            replicas: 3

    proxy:
        image: markgowans/nginx
        ports:
            - 8888:80
        networks:
            - app
        depends_on:
            - flaskapp
        deploy:
            replicas: 1

    redis:
        image: redis
        networks:
            - app
        deploy:
            replicas: 1
networks:
    app:
        driver: overlay

