version: '3'
services:
    flaskapp:
        build: ./flaskapp
        image: flaskapp
        networks:
            - "app"
        command: python app.py
        deploy:
            replicas: 3

    proxy:
        build: ./proxy
        image: proxy
        ports:
            - "8888:80"
        networks:
            - "app"
        depends_on:
            - "flaskapp"
        deploy:
            replicas: 1

    redis:
        image: redis
        networks:
            - "app"
        deploy:
            replicas: 1
networks:
    app:
        driver: overlay

